name: Preview

on:
  workflow_run:
    workflows: [ci, CI]
    types: [completed]

permissions:
  contents: read
  actions: read
  pull-requests: write
  id-token: write

jobs:
  publish:
    uses: anomaly51/general-1-argocd/.github/workflows/publish-preview.yaml@18f7ccfdc6c3cc4677a78013660e3a023afb1c1c
    with:
      service: traffic-mfe
